project:
  type: website

website:
  title: "Austin Barish"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Data Visualizations Final Project
        file: ./spring2023-project-team-4/website/index.html

format:
  html:
    theme: lux
    css: styles.css
    toc: true



