project:
  type: website

website:
  search: false
  site-url: austinbarish.georgetown.domains
  navbar:
    title: Austin Barish
    background: primary
    pinned: true
    search: false
    left:
      - href: index.qmd
        text: About
      - href: coursework.qmd
        text: Coursework
      - text: Passion Projects
        menu:
          - text: NBA Player Guesser
            href: https://austinbarish.shinyapps.io/nbaguesser/
          - text: DC Restaurant Grid
            href: https://austinbarish.shinyapps.io/restaurantgrid/
          - text: NBA Embedding comparison (Coming Soon)

    right:
      - text: Resume
        file: ./Resume.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/austin-barish/
        target: _blank
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/austinbarish
        target: _blank
        aria-label: GitHub
      
      

format:
  html:
    theme: 
      - lux
      - custom.scss
    css: styles.css
    toc: true



