# to render `cd` to the code directoy and run `quarto render` (just those 2 commands)

project:
  type: website
  output-dir: ../website

website:
  title: Website {{< var topic.name >}}
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: geospatial.qmd
        text: Geospatial      
      - href: plot-2.qmd
        text: plot-2      
      - href: plot-3.qmd
        text: plot-3      
      - href: plot-4.qmd
        text: plot-4      
      - href: plot-5.qmd
        text: plot-5
  page-footer:
    left: |
      Project by Group 4 <br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

