# to render `cd` to the code directoy and run `quarto render` (just those 2 commands)

project:
  type: website
  output-dir: ../website

website:
  title: Website {{< var topic.name >}}
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: the_fdic.qmd
        text: The FDIC        
      - href: methods.qmd
        text: Methods        
      - href: code.qmd
        text: Code        
      - href: methods.qmd
        text: Methods        
      - href: authors.qmd
        text: Authors        
  page-footer:
    left: |
      Project by Group 4 <br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib
