# The FDIC {#welcome .unnumbered}


# Introduction

On Friday, March 10th, 2023, U.S. regulators seized Silicon Valley Bank (SVB) in the largest U.S. bank failure since the 2008 financial crisis. The 40-year-long bank operation suddenly stopped after depositors panicked when learning that the bank was short on capital. The bank found itself in this position due to several factors, including incorrect investment allocation and customers requiring to use more cash in the bank as Venture Capital firms cut back their funding @vanian_heres_2023. The public quickly turned its attention to the Federal Deposit Insurance Corporation (FDIC). The FDIC is an independent government agency tasked with insuring deposits, supervising financial institutions, and dealing with the orderly management of a bank failure. Most famously,  the FDIC provides a standard insurance amount of $250,000 per depositor, per insured bank, which has accomplished for no depositor to lose a penny of insured funds due to a failure since 1934 @federal_deposit_insurance_corporation_what_2020. It became apparent that the general public needed to be made aware of the FDIC system, its role in the financial system, and its importance in preserving the financial well-being of the U.S. population. In this report, we seek to provide a glimpse into the FDIC system and offer a rich visual representation of the system's mechanics.
